#Check if LibVNC is installed on the system
find_package(PkgConfig)
pkg_check_modules(PC_LIBVNCCLIENT QUIET libvncclient)
set(LIBVNCCLIENT_DEFINITIONS ${PC_LIBVNCCLIENT_CFLAGS_OTHER})

find_path(LIBVNCCLIENT_INCLUDE_DIR rfb/rfb.h HINTS ${PC_LIBVNCCLIENT_INCLUDEDIR} ${PC_LIBVNCCLIENT_INCLUDE_DIRS})

find_library(LIBVNCCLIENT_LIBRARY NAMES vncclient libvncclient HINTS ${PC_LIBVNCCLIET_LIBDIR} ${PC_LIBVNCCLIENT_LIBRARY_DIRS})

set(LIBVNCCLIENT_LIBRARIES ${LIBVNCCLIENT_LIBRARY} )
set(LIBVNCCLIET_INCLUDE_DIRS ${LIBVNCCLIENT_INCLUDE_DIR} )
